package jp.kaiz.byuuun;

import com.mojang.realmsclient.gui.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.entity.EntityPlayerSP;
import net.minecraft.client.gui.GuiScreen;
import net.minecraft.client.settings.KeyBinding;
import net.minecraft.entity.player.PlayerCapabilities;
import net.minecraft.init.SoundEvents;
import net.minecraftforge.common.config.ConfigElement;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.client.IModGuiFactory;
import net.minecraftforge.fml.client.config.GuiConfig;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.InputEvent;
import org.lwjgl.input.Keyboard;

import java.util.Set;

@Mod(modid = Byuuun.MODID, name = Byuuun.NAME, version = Byuuun.VERSION, guiFactory = "jp.kaiz.byuuun.Byuuun", clientSideOnly = true)
public class Byuuun implements IModGuiFactory {
    public static final String MODID = "byuuun";
    public static final String NAME = "Byuuun";
    public static final String VERSION = "1.0";

    @Mod.Metadata(MODID)
    private static ModMetadata meta;

    private static final KeyBinding KEY_TOGGLE = new KeyBinding("key.byuuun.toggle", Keyboard.KEY_NONE, "key.category.byuuun");

    public static Configuration cfg;
    public static final String CATEGORY_SPEED = "speed";

    public static float speed = 3.0f;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        Byuuun.registerMetadata(meta);
        Byuuun.cfg = new Configuration(event.getSuggestedConfigurationFile());
        cfg.load();
        this.syncConfig();
        ClientRegistry.registerKeyBinding(KEY_TOGGLE);
    }

    public static void registerMetadata(ModMetadata meta) {
        meta.modId = MODID;
        meta.name = NAME;
        meta.version = VERSION;
        meta.authorList.add("Twitter@Kaiz_JP");
        meta.description = "びゅーーーん";
        meta.url = "https://github.com/Kai-Z-JP/Byuuun";
        meta.autogenerated = false;
    }

    @Mod.EventHandler
    public void init(FMLPreInitializationEvent event) {
        FMLCommonHandler.instance().bus().register(this);
    }

    @SubscribeEvent
    public void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent event) {
        if (event.getModID().equals(Byuuun.MODID)) {
            this.syncConfig();
        }
    }

    public void syncConfig() {
        speed = cfg.getFloat(Byuuun.CATEGORY_SPEED, "speed", 3.0f, 0.0f, 10.0f, "Speed");
        cfg.save();
    }

    @SubscribeEvent
    public void onInput(InputEvent event) {
        if (KEY_TOGGLE.isPressed()) {
            Minecraft minecraft = Minecraft.getMinecraft();
            EntityPlayerSP player = minecraft.player;
            PlayerCapabilities capabilities = player.capabilities;

            capabilities.setFlySpeed((capabilities.getFlySpeed() == 0.05f ? speed : 1) / 20f);
            player.playSound(SoundEvents.UI_BUTTON_CLICK, 1.0F, 1.0F);
            minecraft.ingameGUI.setOverlayMessage(
                    "Fly Speed" + ChatFormatting.GRAY + ": " + ChatFormatting.GREEN + capabilities.getFlySpeed() * 20,
                    false
            );
        }
    }


    @Override
    public void initialize(Minecraft minecraftInstance) {
    }

    @Override
    public boolean hasConfigGui() {
        return true;
    }

    @Override
    public GuiScreen createConfigGui(GuiScreen parentScreen) {
        return new ByuuunConfigGui(parentScreen);
    }

    @Override
    public Set<IModGuiFactory.RuntimeOptionCategoryElement> runtimeGuiCategories() {
        return null;
    }

    public static class ByuuunConfigGui extends GuiConfig {
        public ByuuunConfigGui(GuiScreen parentScreen) {
            super(parentScreen, new ConfigElement(Byuuun.cfg.getCategory(Byuuun.CATEGORY_SPEED)).getChildElements(), Byuuun.MODID, false, false, Byuuun.NAME);
        }
    }
}
